schema_version: 1

context:
  version: "1.91.0"

package:
  name: dependabot-cli
  version: ${{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v${{ version }}.tar.gz
  sha256: 79b9dd669d39390fe8ea4c8376822774534f0234cffbe7db85bc28aebd23312b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dependabot --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  homepage: https://github.com/dependabot/cli
  repository: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
