schema_version: 1

context:
  version: "1.89.0"

package:
  name: dependabot-cli
  version: ${{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v${{ version }}.tar.gz
  sha256: c4c0ecd583dfe8142357e31c95f390e19e8a24687bcd0350c801b68da2d03581

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dependabot --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  homepage: https://github.com/dependabot/cli
  repository: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
