schema_version: 1

context:
  version: "1.92.0"

package:
  name: dependabot-cli
  version: ${{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v${{ version }}.tar.gz
  sha256: 11a6cbbb69b75428a0abcd85f7e118c87ba18b2d00cc56b3dcf52379e0f54ca3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dependabot --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  homepage: https://github.com/dependabot/cli
  repository: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
